# Generated by Django 4.0.4 on 2022-05-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(max_length=20, verbose_name='Название магазина')),
                ('shopCity', models.CharField(max_length=20, verbose_name='Город')),
                ('shopStreet', models.CharField(max_length=25, verbose_name='Улица')),
                ('shopHouse', models.IntegerField(verbose_name='Дом')),
                ('shopTO', models.TimeField(verbose_name='Время открытия')),
                ('shopTC', models.TimeField(verbose_name='Время закрытия')),
            ],
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
